export const reduxActionTypes = {
    SET_POSTS: 'SET_POSTS',
    GET_MORE_POSTS: 'GET_MORE_POSTS',
    SET_POSTS_HAS_MORE: 'SET_POSTS_HAS_MORE',
    INCREMENT_COUNT: 'INCREMENT_COUNT',
    DECREMENT_COUNT: 'DECREMENT_COUNT',
}